#!/usr/bin/env python3
"""Produce host-build copies of source files that cannot compile unmodified.

Some target-only constructs are hard errors on a 64-bit host compiler, the
classic one being a 32-bit vector table that stores function addresses:

    uint32 const BootVector[] = { (uint32)(uint32 *)&Reset_Handler, ... };
    -> error: initializer element is not constant   (address truncated to 32 bit)

The construct itself is never executed on the host, but the whole file is
rejected, so the units in it cannot be tested at all.  Rather than editing the
source or keeping a hand-patched copy that silently drifts, this tool writes
the copy at build time from a list of *literal* replacements declared in
ut_spec.json, each with its reason:

    "host_shims": [
      {
        "file": "code/Source/DRV/DMCU/DMCU_cfg.c",
        "out":  "support/DMCU_cfg_host.c",
        "replacements": [
          {"old": "(const uint32 )((uint32 *)&MCU_vidFastWkupBootAddress),",
           "new": "0u,",
           "why": "function address truncated to 32 bit is not a constant on the host; the table is inactive (DCMRWF5 setup is compiled out)"}
        ]
      }
    ]

Rules that keep this honest:
  * every `old` must occur exactly once, otherwise the tool fails - a source
    change that moves the construct is noticed, not papered over;
  * a replacement may not change the line count, and the copy starts with a
    `#line 1 "<original>"` directive, so gcov / cppcheck / the evidence report
    attribute every line to the *original* file and the coverage annotation is
    the real source;
  * the shim list is printed by build_evidence.py in the configuration section
    (the reviewer must see what was not compiled verbatim).

    python scripts/gen_host_shim.py --spec ut_spec.json [--root .]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--spec', type=Path, required=True)
    ap.add_argument('--root', type=Path, default=Path('.'))
    args = ap.parse_args()

    spec = json.loads(args.spec.read_text(encoding='utf-8'))
    shims = spec.get('host_shims') or []
    if not shims:
        print('no host_shims in spec; nothing to do')
        return 0
    out_dir = args.root / spec['output_dir']
    for shim in shims:
        src = args.root / shim['file']
        text = src.read_text(encoding='utf-8', errors='replace')
        for r in shim['replacements']:
            n = text.count(r['old'])
            if n != 1:
                print(f'ERROR: {src}: replacement text found {n} times (must be 1):\n  {r["old"]!r}')
                return 1
            if r['old'].count('\n') != r['new'].count('\n'):
                print(f'ERROR: {src}: replacement changes the line count:\n  {r["old"]!r}')
                return 1
            text = text.replace(r['old'], r['new'], 1)
        target = out_dir / shim['out']
        target.parent.mkdir(parents=True, exist_ok=True)
        posix = src.resolve().as_posix()
        # Line comments: the replaced text may itself contain "*/".
        def one(t: str) -> str:
            return ' '.join(t.split())
        header = (f'// HOST BUILD COPY of {shim["file"]} - generated by gen_host_shim.py, do not edit.\n'
                  + ''.join(f'//   - {one(r["old"])}  ->  {one(r["new"])}\n//     why: {one(r["why"])}\n'
                            for r in shim['replacements'])
                  + '//   #line keeps coverage and diagnostics on the original file.\n'
                  + f'#line 1 "{posix}"\n')
        target.write_text(header + text, encoding='utf-8', newline='\n')
        print(f'wrote {target} ({len(shim["replacements"])} replacements)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
