#!/usr/bin/env python3
"""Write a Ceedling project.yml skeleton from ut_spec.json.

Keeps include dirs, defines and CMock type names in one place (ut_spec.json)
so the Ceedling build, cppcheck and the evidence report all see the same
values.  Paths in ut_spec are relative to the project root; project.yml lives
in <output_dir>, so they are rewritten relative to it and directories that do
not exist are dropped (Ceedling refuses to start otherwise).

Spec keys used: component, output_dir, source_dirs, include_dirs, defines,
cmock_treat_as (optional mapping of project typedef names to CMock types),
compile_flags (optional extra gcc flags for every test compile, e.g.
`--include=ut_host_regs.h` to redirect fixed-address register blocks),
link_flags (optional, e.g. `-Wl,--allow-multiple-definition` so a test file
can override an internal function of a separately linked source object).

    python scripts/gen_project_yml.py --spec unit_test/<module>/ut_spec.json [--force]
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

TEMPLATE = """---
# Ceedling project for SWE.4 unit verification of {component}
# (generated by gen_project_yml.py from ut_spec.json - edit ut_spec, then regenerate).
#
# Whole-TU method: the test files #include the module's .c file, so the module
# directory is on :paths :include, NOT on :paths :source.  support/ only holds
# what the real headers cannot provide on the host (base types, OS facade,
# definitions of extern data objects the module reads).

:project:
  :build_root: build
  :use_test_preprocessor: :all
  :use_mocks: TRUE
  :use_exceptions: FALSE
  :test_file_prefix: test_
  :default_tasks:
    - test:all

:paths:
  :test:
    - test
  :source:
    - support
  :include:
    - support
{includes}
  :support:
    - support

:defines:
  :test:
    - UNIT_TEST
{defines}

:flags:
  :test:
    :compile:
      :*:
        - -std=gnu99
        - -Wall
        - -Wno-unused-function
        - -Wno-unused-variable
        - -Wno-unused-but-set-variable
        - -Wno-attributes
        - -fno-common
{compile_flags}
    :link:
      :*:
{link_flags}

:unity:
  :defines:
    - UNITY_INCLUDE_DOUBLE
    - UNITY_SUPPORT_64

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: FALSE
  # Prototypes declared with `extern` are skipped by default -> empty mocks.
  :treat_externs: :include
  :plugins:
    - :ignore
    - :array
    - :expect_any_args
    - :ignore_arg
    - :callback
    - :return_thru_ptr
  # Every project typedef name CMock must compare as a plain integer.
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    sint8:    INT8
    sint16:   INT16
    sint32:   INT32
    boolean:  UINT8
    bool:     UINT8
{treat_as}

:gcov:
  :utilities:
    - gcovr
  # No :reports: on purpose - coverage reporting is owned by build_evidence.py.
  :gcovr:
    :branches: TRUE

:plugins:
  :enabled:
    - report_tests_pretty_stdout
    - gcov
...
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--spec', type=Path, required=True)
    ap.add_argument('--root', type=Path, default=Path('.'))
    ap.add_argument('--force', action='store_true')
    args = ap.parse_args()

    spec = json.loads(args.spec.read_text(encoding='utf-8'))
    out_dir = args.root / spec['output_dir']
    target = out_dir / 'project.yml'
    if target.exists() and not args.force:
        print(f'{target} exists; use --force to overwrite')
        return 1
    dirs = list(spec.get('source_dirs', [])) + list(spec.get('include_dirs', []))
    seen, rel, dropped = set(), [], []
    for d in dirs:
        if d in seen:
            continue
        seen.add(d)
        if not (args.root / d).is_dir():
            dropped.append(d)
            continue
        rel.append(os.path.relpath(args.root / d, out_dir).replace('\\', '/'))
    includes = '\n'.join(f'    - {r}' for r in rel)
    defines = '\n'.join(f'    - {d}' for d in spec.get('defines', []))
    treat = '\n'.join(f'    {k}: {v}' for k, v in (spec.get('cmock_treat_as') or {}).items())
    cflags = '\n'.join(f'        - {f}' for f in spec.get('compile_flags', []))
    lflags = '\n'.join(f'        - {f}' for f in spec.get('link_flags', []))
    out_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(TEMPLATE.format(component=spec.get('component', ''), includes=includes,
                                      defines=defines, treat_as=treat, compile_flags=cflags, link_flags=lflags),
                      encoding='utf-8', newline='\n')
    print(f'wrote {target} ({len(rel)} include dirs, {len(spec.get("defines", []))} defines)')
    for d in dropped:
        print(f'  dropped non-existent include dir: {d}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
